// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmc1og2DcJw8wfuGaK9jrPyymeADGVaz4',
    appId: '1:481598051103:web:245b786a01a1739b3b962a',
    messagingSenderId: '481598051103',
    projectId: 'evently-c27fd',
    authDomain: 'evently-c27fd.firebaseapp.com',
    storageBucket: 'evently-c27fd.firebasestorage.app',
    measurementId: 'G-4XS8SMZPJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw6tikpTHQuCkn9BSCDwcT54ouSF2FQIY',
    appId: '1:481598051103:android:caeece75d8d738873b962a',
    messagingSenderId: '481598051103',
    projectId: 'evently-c27fd',
    storageBucket: 'evently-c27fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi-j2oYWcfgxPJyPqRFp3DPreYOHDWFx4',
    appId: '1:481598051103:ios:de6fa57d4def103e3b962a',
    messagingSenderId: '481598051103',
    projectId: 'evently-c27fd',
    storageBucket: 'evently-c27fd.firebasestorage.app',
    iosBundleId: 'com.example.event',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi-j2oYWcfgxPJyPqRFp3DPreYOHDWFx4',
    appId: '1:481598051103:ios:de6fa57d4def103e3b962a',
    messagingSenderId: '481598051103',
    projectId: 'evently-c27fd',
    storageBucket: 'evently-c27fd.firebasestorage.app',
    iosBundleId: 'com.example.event',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmc1og2DcJw8wfuGaK9jrPyymeADGVaz4',
    appId: '1:481598051103:web:4983b00b196051623b962a',
    messagingSenderId: '481598051103',
    projectId: 'evently-c27fd',
    authDomain: 'evently-c27fd.firebaseapp.com',
    storageBucket: 'evently-c27fd.firebasestorage.app',
    measurementId: 'G-VYJH7LSE0P',
  );
}
